version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: airline-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airline_db
      MYSQL_USER: airline
      MYSQL_PASSWORD: airline123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: jeffreypp/airline-order-backend:v1.0
    container_name: airline-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airline_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: airline
      SPRING_DATASOURCE_PASSWORD: airline123

volumes:
  db_data:
